// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCD4dPu8zarNEYjTKlyT679C2wTfbO-xhk',
    appId: '1:773998890971:web:9d87270f573b3f038421fe',
    messagingSenderId: '773998890971',
    projectId: 'oposiwork-99cc1',
    authDomain: 'oposiwork-99cc1.firebaseapp.com',
    storageBucket: 'oposiwork-99cc1.firebasestorage.app',
    measurementId: 'G-14V241967L',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCD4dPu8zarNEYjTKlyT679C2wTfbO-xhk',
    appId: '1:773998890971:web:88b82934440e21f38421fe',
    messagingSenderId: '773998890971',
    projectId: 'oposiwork-99cc1',
    authDomain: 'oposiwork-99cc1.firebaseapp.com',
    storageBucket: 'oposiwork-99cc1.firebasestorage.app',
    measurementId: 'G-DCHSXWZ12S',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAR53sMZgkWud6rxWPvSqS4EAT1EUlykhw',
    appId: '1:773998890971:ios:8f99d18b15e3b4158421fe',
    messagingSenderId: '773998890971',
    projectId: 'oposiwork-99cc1',
    storageBucket: 'oposiwork-99cc1.firebasestorage.app',
    iosBundleId: 'com.example.oposifinal',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0nBuOAW5Cvcbm5BFf8x29xm_XM1kArXM',
    appId: '1:773998890971:android:567acab193d8636d8421fe',
    messagingSenderId: '773998890971',
    projectId: 'oposiwork-99cc1',
    storageBucket: 'oposiwork-99cc1.firebasestorage.app',
  );

}